micronaut:
  application:
    name: relatorioMs
  server:
    port: 8082

mongodb:
  uri: 'mongodb://localhost:27017/vendas'

kafka:
  bootstrap:
    servers: localhost:9092

consul:
  client:
    registration:
      enabled: true
    defaultZone: "localhost:8500"