micronaut:
  application:
    name: veiculoMs
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/dbveiculoms
    driverClassName: org.postgresql.Driver
    username: root
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - 'br.com.jonataslaet.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true
        format-sql: true

consul:
  client:
    registration:
      enabled: true
    defaultZone: "localhost:8500"